/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next')['BInputGroupText']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTfoot: typeof import('bootstrap-vue-next')['BTfoot']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    CForm: typeof import('./src/components/cForm.vue')['default']
    CInputGroup: typeof import('./src/components/cInputGroup.vue')['default']
    FormController: typeof import('./src/pages/FormController.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
